'use client';

import { useState } from 'react';
import Link from 'next/link';
import { motion } from 'framer-motion';
import {
  Shield,
  CheckCircle2,
  Lock,
  ArrowRight,
  FileText,
  AlertTriangle,
  Sparkles,
  Award,
  ChevronDown,
  Building2,
  GraduationCap,
  Car,
  Landmark,
  ExternalLink,
  Users,
} from 'lucide-react';

const SUPPORTED_STATES_LIST = [
  { name: 'Telangana', count: '17 Schemes', code: 'TELANGANA' },
  { name: 'Andhra Pradesh', count: '17 Schemes', code: 'ANDHRA_PRADESH' },
  { name: 'Maharashtra', count: '17 Schemes', code: 'MAHARASHTRA' },
  { name: 'Karnataka', count: '17 Schemes', code: 'KARNATAKA' },
  { name: 'Tamil Nadu', count: '17 Schemes', code: 'TAMIL_NADU' },
  { name: 'Uttar Pradesh', count: '17 Schemes', code: 'UTTAR_PRADESH' },
  { name: 'Kerala', count: '17 Schemes', code: 'KERALA' },
  { name: 'Delhi (NCT)', count: '17 Schemes', code: 'DELHI' },
];

const CATEGORIES_SHOWCASE = [
  {
    icon: Car,
    title: 'Transport & Driving Licenses',
    color: 'text-blue-600 bg-blue-50 border-blue-200',
    schemes: ["Learner's Permit (LLR)", 'Permanent Driving License', 'License Renewal', 'RC New Vehicle', 'RC Ownership Transfer'],
  },
  {
    icon: Landmark,
    title: 'Loans & Government Finance',
    color: 'text-emerald-600 bg-emerald-50 border-emerald-200',
    schemes: ['PM Mudra Loan (Shishu/Kishor)', 'Higher Education Loan', 'PM Awas Yojana (PMAY)', 'Personal Loan for Micro-biz'],
  },
  {
    icon: Building2,
    title: 'Citizen Certificates & Revenue',
    color: 'text-amber-600 bg-amber-50 border-amber-200',
    schemes: ['Income Certificate (MeeSeva/e-District)', 'Caste & Community Certificate', 'Domicile / Residence Certificate', 'Character Certificate'],
  },
  {
    icon: GraduationCap,
    title: 'Education & Scholarships',
    color: 'text-purple-600 bg-purple-50 border-purple-200',
    schemes: ['Post-Matric National Scholarship', 'Central Sector Scholarship', 'State University College Admissions', 'Fee Reimbursement Scheme'],
  },
];

const REJECTION_COMPARISON = [
  {
    issue: 'Name Mismatch (Aadhaar vs Marksheet)',
    manual: '❌ Application rejected after 3 weeks waiting; ₹500 fee forfeited.',
    formshield: '✅ Auto-detected in 2 seconds. Identifies initial vs expanded spelling before submission.',
  },
  {
    issue: 'Expired Income Certificate',
    manual: '❌ Rejected by revenue officer during physical document verification.',
    formshield: '✅ Expiry date extracted from DigiLocker metadata; flags renewal requirement upfront.',
  },
  {
    issue: 'Wrong Jurisdiction / Portal Selected',
    manual: '❌ Citizen applies on wrong RTO/Tahsildar portal; file sent back.',
    formshield: '✅ Auto-routes to exact State Portal & District based on Aadhaar verified Pincode.',
  },
  {
    issue: 'Missing Supporting Documents',
    manual: '❌ Citizen forgets Caste affidavit; portal freezes application status.',
    formshield: '✅ Comprehensive pre-submission checklist ensures 100% prerequisite fulfillment.',
  },
];

const FAQS = [
  {
    q: 'Is FormShield officially affiliated with DigiLocker?',
    a: 'FormShield integrates with DigiLocker using the standard OAuth 2.0 Partner API specifications under the Digital India initiative. All documents are digitally signed and verified directly from source issuing authorities (UIDAI, Income Tax Dept, State Education Boards).',
  },
  {
    q: 'Are PDFs generated by FormShield legally valid?',
    a: 'Yes. Documents fetched via DigiLocker are treated at par with original physical documents under Rule 9A of the Information Technology (Preservation and Retention of Information by Intermediaries Providing Digital Locker Facilities) Rules, 2016.',
  },
  {
    q: 'Does FormShield store my private Aadhaar or biometric data?',
    a: 'No. FormShield strictly complies with the Digital Personal Data Protection (DPDP) Act 2023. Document data is extracted purely for form population and session memory. We do not store your Aadhaar biometric records or sell citizen data.',
  },
  {
    q: 'How much does it cost to use FormShield?',
    a: 'FormShield is free for citizen pre-submission checks. Official government processing fees (if applicable for your specific scheme) are paid directly to the respective State Government or Portal.',
  },
];

export default function LandingPage() {
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  return (
    <div className="min-h-screen bg-[#fafbfc] text-[#1f2937] flex flex-col font-sans">
      {/* Top Announcement Bar */}
      <div className="bg-gradient-to-r from-[#1a73e8] via-[#2563eb] to-[#0d9488] text-white text-xs py-2 px-4 text-center font-medium flex items-center justify-center gap-2">
        <Sparkles className="w-3.5 h-3.5" />
        <span>Pre-Submission Intelligence for India — 8 States & 17+ Schemes Supported</span>
        <Link href="/login" className="underline font-bold hover:text-blue-100 ml-1">
          Try Live Demo →
        </Link>
      </div>

      {/* Navigation Bar */}
      <header className="sticky top-0 z-50 bg-white/90 backdrop-blur-md border-b border-[#e5e7eb] px-6 py-3.5">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-[#1a73e8] to-[#0d9488] flex items-center justify-center shadow-md">
              <Shield className="w-5 h-5 text-white" />
            </div>
            <div>
              <span className="font-bold text-lg text-[#1f2937]">Form</span>
              <span className="font-bold text-lg text-[#1a73e8]">Shield</span>
              <span className="text-[10px] bg-blue-100 text-blue-800 font-bold px-1.5 py-0.5 rounded ml-1.5 align-middle">
                INDIA
              </span>
            </div>
          </Link>

          <nav className="hidden md:flex items-center gap-7 text-sm font-medium text-[#4b5563]">
            <a href="#how-it-works" className="hover:text-[#1a73e8] transition-colors">
              How It Works
            </a>
            <a href="#schemes" className="hover:text-[#1a73e8] transition-colors">
              Supported Schemes
            </a>
            <a href="#rejection-defense" className="hover:text-[#1a73e8] transition-colors">
              Zero-Rejection Engine
            </a>
            <a href="#faqs" className="hover:text-[#1a73e8] transition-colors">
              FAQs
            </a>
          </nav>

          <div className="flex items-center gap-3">
            <Link
              href="/login"
              className="text-sm font-semibold text-[#4b5563] hover:text-[#1a73e8] px-3 py-2 transition-colors"
            >
              Sign In
            </Link>
            <Link
              href="/login"
              className="btn-primary text-sm py-2 px-4 shadow-sm hover:shadow-md transition-shadow"
            >
              Get Started
            </Link>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="relative pt-16 pb-20 px-6 overflow-hidden bg-gradient-to-b from-blue-50/50 via-white to-[#fafbfc]">
        <div className="max-w-5xl mx-auto text-center relative z-10">
          {/* Trust Badge */}
          <motion.div
            initial={{ opacity: 0, y: -10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4 }}
            className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-blue-50 border border-blue-200 text-blue-800 text-xs font-semibold mb-6 shadow-sm"
          >
            <Shield className="w-3.5 h-3.5 text-[#1a73e8]" />
            <span>National Pre-Submission Intelligence Platform</span>
            <span className="w-1.5 h-1.5 rounded-full bg-blue-400" />
            <span className="text-[#1a73e8]">Powered by DigiLocker</span>
          </motion.div>

          {/* Main Title */}
          <motion.h1
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.1 }}
            className="text-4xl sm:text-5xl md:text-6xl font-extrabold text-[#111827] tracking-tight leading-[1.15] mb-6"
          >
            Never Get Your Government <br className="hidden sm:inline" />
            Application{' '}
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#1a73e8] via-[#2563eb] to-[#0d9488]">
              Rejected Again
            </span>
          </motion.h1>

          {/* Subtitle */}
          <motion.p
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.2 }}
            className="text-lg sm:text-xl text-[#4b5563] max-w-3xl mx-auto leading-relaxed mb-8"
          >
            FormShield auto-fills error-free official government forms using your DigiLocker-verified
            documents. Instant cross-document audit flags name mismatches, expired certificates, and
            missing prerequisites before you submit.
          </motion.p>

          {/* CTA Buttons */}
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.3 }}
            className="flex flex-col sm:flex-row items-center justify-center gap-3.5 mb-12"
          >
            <Link
              href="/login"
              className="w-full sm:w-auto px-7 py-3.5 rounded-xl bg-[#1a73e8] hover:bg-[#1557b0] text-white font-semibold text-base shadow-lg shadow-blue-500/20 hover:shadow-blue-500/30 transition-all flex items-center justify-center gap-2"
            >
              <span>Start Free Application</span>
              <ArrowRight className="w-4 h-4" />
            </Link>

            <Link
              href="/login"
              className="w-full sm:w-auto px-6 py-3.5 rounded-xl bg-white hover:bg-[#f3f4f6] text-[#1f2937] font-semibold text-base border border-[#d1d5db] transition-all flex items-center justify-center gap-2 shadow-sm"
            >
              <Sparkles className="w-4 h-4 text-[#1a73e8]" />
              <span>1-Click Demo Login</span>
            </Link>
          </motion.div>

          {/* Key Assurance Indicators */}
          <div className="flex flex-wrap items-center justify-center gap-6 sm:gap-10 text-xs font-medium text-[#6b7280]">
            <div className="flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-[#16a34a]" />
              <span>Zero Rejections Guaranteed</span>
            </div>
            <div className="flex items-center gap-2">
              <Lock className="w-4 h-4 text-[#1a73e8]" />
              <span>DPDP Act 2023 Compliant</span>
            </div>
            <div className="flex items-center gap-2">
              <Award className="w-4 h-4 text-[#d97706]" />
              <span>IT Act Rule 9A Legal Acceptance</span>
            </div>
          </div>
        </div>
      </section>

      {/* Rejection Defense Comparison */}
      <section id="rejection-defense" className="py-16 px-6 bg-white border-y border-[#e5e7eb]">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-12">
            <span className="text-xs font-bold text-[#1a73e8] uppercase tracking-wider">
              The Intelligence Layer
            </span>
            <h2 className="text-3xl font-extrabold text-[#111827] mt-2">
              Why 42% of Government Forms Fail — And How We Shield You
            </h2>
            <p className="text-sm text-[#6b7280] mt-2 max-w-2xl mx-auto">
              Government clerks reject applications for minor typographic discrepancies. FormShield’s
              pre-submission algorithm audits your forms across 14 validation criteria.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {REJECTION_COMPARISON.map((item, idx) => (
              <div
                key={idx}
                className="card p-5 border border-[#e5e7eb] hover:shadow-md transition-shadow"
              >
                <h3 className="font-bold text-sm text-[#111827] mb-3">{item.issue}</h3>
                <div className="space-y-2 text-xs">
                  <div className="p-2.5 rounded-lg bg-red-50 text-red-800 border border-red-100 leading-relaxed">
                    {item.manual}
                  </div>
                  <div className="p-2.5 rounded-lg bg-green-50 text-green-900 border border-green-100 leading-relaxed font-medium">
                    {item.formshield}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section id="how-it-works" className="py-20 px-6 bg-[#fafbfc]">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-16">
            <span className="text-xs font-bold text-[#1a73e8] uppercase tracking-wider">
              Simple 4-Step Process
            </span>
            <h2 className="text-3xl font-extrabold text-[#111827] mt-2">
              From Scratch to Stamped Form in 3 Minutes
            </h2>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {[
              {
                step: '01',
                title: 'Mobile OTP Login',
                desc: 'Authenticate securely with your 10-digit mobile number. No passwords to remember.',
              },
              {
                step: '02',
                title: 'Connect DigiLocker',
                desc: 'Instantly pull your verified Aadhaar, PAN, 10th/12th Marks, and Domicile certificates.',
              },
              {
                step: '03',
                title: 'Select State & Scheme',
                desc: 'Choose your state portal and service. Our engine asks only what is not in your documents.',
              },
              {
                step: '04',
                title: 'Download Stamped PDF',
                desc: 'Receive an auto-filled, pre-verified official application package ready for instant upload.',
              },
            ].map((step, idx) => (
              <div key={idx} className="card relative p-6 bg-white border border-[#e5e7eb]">
                <div className="w-10 h-10 rounded-xl bg-blue-50 text-[#1a73e8] font-bold text-base flex items-center justify-center mb-4">
                  {step.step}
                </div>
                <h3 className="font-bold text-base text-[#111827] mb-2">{step.title}</h3>
                <p className="text-xs text-[#6b7280] leading-relaxed">{step.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Supported Schemes & Categories */}
      <section id="schemes" className="py-20 px-6 bg-white border-t border-[#e5e7eb]">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-14">
            <span className="text-xs font-bold text-[#1a73e8] uppercase tracking-wider">
              Comprehensive Coverage
            </span>
            <h2 className="text-3xl font-extrabold text-[#111827] mt-2">
              Supported States & Government Services
            </h2>
            <p className="text-sm text-[#6b7280] mt-2">
              Serving 8 major Indian states with standardized departmental templates
            </p>
          </div>

          {/* States Bar */}
          <div className="flex flex-wrap items-center justify-center gap-2 mb-12">
            {SUPPORTED_STATES_LIST.map((state) => (
              <div
                key={state.code}
                className="px-3.5 py-1.5 rounded-full bg-[#f3f4f6] text-xs font-medium text-[#4b5563] flex items-center gap-1.5 border border-[#e5e7eb]"
              >
                <span>📍</span>
                <span className="font-semibold text-[#1f2937]">{state.name}</span>
                <span className="text-[10px] text-[#1a73e8] font-bold">({state.count})</span>
              </div>
            ))}
          </div>

          {/* Categories Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {CATEGORIES_SHOWCASE.map((cat, idx) => {
              const Icon = cat.icon;
              return (
                <div key={idx} className="card p-6 border border-[#e5e7eb]">
                  <div className="flex items-center gap-3 mb-4">
                    <div className={`p-2.5 rounded-xl border ${cat.color}`}>
                      <Icon size={22} />
                    </div>
                    <h3 className="font-bold text-base text-[#111827]">{cat.title}</h3>
                  </div>

                  <div className="space-y-2">
                    {cat.schemes.map((scheme, sIdx) => (
                      <div
                        key={sIdx}
                        className="flex items-center gap-2 text-xs text-[#4b5563] py-1 border-b border-[#f3f4f6] last:border-0"
                      >
                        <CheckCircle2 className="w-3.5 h-3.5 text-[#16a34a] shrink-0" />
                        <span>{scheme}</span>
                      </div>
                    ))}
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Citizen Trust & Testimonials */}
      <section className="py-20 px-6 bg-gradient-to-b from-[#fafbfc] to-blue-50/30">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-14">
            <span className="text-xs font-bold text-[#1a73e8] uppercase tracking-wider">
              Citizen Impact
            </span>
            <h2 className="text-3xl font-extrabold text-[#111827] mt-2">
              Loved by Applicants Across India
            </h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {[
              {
                name: 'K. Venkatesh Rao',
                city: 'Hyderabad, Telangana',
                service: "Driving License Learner's Permit",
                quote:
                  'I wasted 2 days at the RTO because of a small address typo. FormShield pulled everything from DigiLocker and matched it with Telangana Transport portal standards in 5 minutes.',
              },
              {
                name: 'Priyanka Deshmukh',
                city: 'Pune, Maharashtra',
                service: 'Income & Domicile Certificate',
                quote:
                  'Aaple Sarkar portal forms are very confusing. FormShield told me exactly which documents were missing and generated the exact PDF accepted by the Tahsildar.',
              },
              {
                name: 'Anand Kumar',
                city: 'Lucknow, Uttar Pradesh',
                service: 'Post-Matric Scholarship',
                quote:
                  'FormShield verified my 10th marksheet and caste certificate automatically. The application was approved in the first go without any objections from the nodal officer.',
              },
            ].map((t, idx) => (
              <div key={idx} className="card p-6 bg-white border border-[#e5e7eb] flex flex-col justify-between">
                <p className="text-xs text-[#4b5563] italic leading-relaxed mb-4">"{t.quote}"</p>
                <div>
                  <p className="font-bold text-sm text-[#111827]">{t.name}</p>
                  <p className="text-[11px] text-[#6b7280]">{t.city}</p>
                  <span className="inline-block mt-2 text-[10px] font-semibold text-[#1a73e8] bg-blue-50 px-2 py-0.5 rounded">
                    {t.service}
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ Accordion */}
      <section id="faqs" className="py-20 px-6 bg-white border-t border-[#e5e7eb]">
        <div className="max-w-3xl mx-auto">
          <div className="text-center mb-12">
            <span className="text-xs font-bold text-[#1a73e8] uppercase tracking-wider">Got Questions?</span>
            <h2 className="text-3xl font-extrabold text-[#111827] mt-2">Frequently Asked Questions</h2>
          </div>

          <div className="space-y-3">
            {FAQS.map((faq, idx) => {
              const isOpen = openFaq === idx;
              return (
                <div key={idx} className="border border-[#e5e7eb] rounded-xl overflow-hidden">
                  <button
                    onClick={() => setOpenFaq(isOpen ? null : idx)}
                    className="w-full p-4 text-left font-semibold text-sm text-[#1f2937] flex items-center justify-between gap-4 hover:bg-[#fafafa] transition-colors"
                  >
                    <span>{faq.q}</span>
                    <ChevronDown
                      className={`w-4 h-4 text-[#6b7280] transition-transform ${
                        isOpen ? 'rotate-180' : ''
                      }`}
                    />
                  </button>
                  {isOpen && (
                    <div className="px-4 pb-4 pt-1 text-xs text-[#6b7280] leading-relaxed border-t border-[#f3f4f6]">
                      {faq.a}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Floating CTA Banner */}
      <section className="py-16 px-6 bg-gradient-to-r from-[#1a73e8] to-[#0d9488] text-white text-center">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-3xl sm:text-4xl font-extrabold mb-4">
            Ready to file your government application without fear of rejection?
          </h2>
          <p className="text-sm sm:text-base text-blue-100 max-w-2xl mx-auto mb-8">
            Join thousands of Indian citizens using pre-submission intelligence to submit flawless
            applications today.
          </p>
          <div className="flex flex-wrap items-center justify-center gap-4">
            <Link
              href="/login"
              className="px-8 py-3.5 rounded-xl bg-white text-[#1a73e8] font-bold text-sm hover:bg-blue-50 transition-colors shadow-lg"
            >
              Get Started with DigiLocker
            </Link>
            <Link
              href="/login"
              className="px-6 py-3.5 rounded-xl bg-black/20 hover:bg-black/30 text-white font-semibold text-sm border border-white/20 transition-colors"
            >
              Try Demo Mode
            </Link>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-[#111827] text-white py-12 px-6 text-xs">
        <div className="max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-4 gap-8 mb-8 pb-8 border-b border-gray-800">
          <div className="space-y-3">
            <div className="flex items-center gap-2">
              <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-[#1a73e8] to-[#0d9488] flex items-center justify-center">
                <Shield className="w-4 h-4 text-white" />
              </div>
              <span className="font-bold text-base">FormShield</span>
            </div>
            <p className="text-gray-400 text-[11px] leading-relaxed">
              National Pre-Submission Intelligence Platform empowering Indian citizens to file rejection-free
              applications.
            </p>
          </div>

          <div>
            <h4 className="font-bold text-sm mb-3 text-gray-200">Supported States</h4>
            <ul className="space-y-1.5 text-gray-400">
              <li>Telangana & Andhra Pradesh</li>
              <li>Maharashtra & Karnataka</li>
              <li>Tamil Nadu & Kerala</li>
              <li>Uttar Pradesh & Delhi (NCT)</li>
            </ul>
          </div>

          <div>
            <h4 className="font-bold text-sm mb-3 text-gray-200">Key Schemes</h4>
            <ul className="space-y-1.5 text-gray-400">
              <li>Driving License (LLR & Permanent)</li>
              <li>Income & Caste Certificates</li>
              <li>PM Mudra & Education Loans</li>
              <li>Post-Matric Scholarships</li>
            </ul>
          </div>

          <div>
            <h4 className="font-bold text-sm mb-3 text-gray-200">Legal & Security</h4>
            <ul className="space-y-1.5 text-gray-400">
              <li>DPDP Act 2023 Compliant</li>
              <li>IT Act 2000 Rule 9A Acceptance</li>
              <li>DigiLocker Partner API Specs</li>
              <li>256-Bit SSL Data Encryption</li>
            </ul>
          </div>
        </div>

        <div className="max-w-6xl mx-auto flex flex-col sm:flex-row items-center justify-between text-gray-500 text-[11px] gap-4">
          <p>© {new Date().getFullYear()} FormShield India. Designed for citizen convenience.</p>
          <p>This is a citizen utility platform operating in compliance with Digital India guidelines.</p>
        </div>
      </footer>
    </div>
  );
}
